version: 2.1

references:
  workspace_root: &workspace_root
    ~/oysteR
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

executors:
  rocker-verse-executor:
    docker:
        - image: rocker/verse:3.6.1
    working_directory: *workspace_root

jobs:
  build:
    executor: rocker-verse-executor
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz --as-cran
      - persist_to_workspace:
          root: *workspace_root
          paths: 
            - oysteR.Rcheck/
  release:
    executor: rocker-verse-executor
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Install Fledge
          command: R -e "devtools::install_github('krlmlr/fledge')"
      - run:
          name: Configure GIT with user info for pushing
          command: |
            git config user.name "$GITHUB_USERNAME"
            git config user.email "$GITHUB_EMAIL"
      - run:
          name: Use Fledge and bump version
          command: R -e "library('fledge'); fledge::bump_version('patch')"
      - run:
          name: Test
          command: git --no-pager log
      - run:
          name: Test
          command: ls -la 
      - run:
          name: Test2
          command: cat DESCRIPTION
      - run:
          name: Check package
          command: R CMD check *tar.gz --as-cran
      - store_artifacts:
          path: ~/oysteR.Rcheck/

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          context: rso-base
          requires:
            - build
