version: 2.1

executors:
  rocker-verse-executor:
    docker:
        - image: rocker/verse:3.6.1
    working_directory: ~/oysteR

jobs:
  build:
    executor: rocker-verse-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz --as-cran
      - persist_to_workspace:
          root: ~/
          paths: 
            - oysteR
  release:
    executor: rocker-verse-executor
    steps:
      - attach_workspace:
          at: ~/oysterR
      - run:
          name: Install Fledge
          command: R -e "devtools::install_github("krlmlr/fledge")"
      - run:
          name: Check package
          command: R CMD check *tar.gz --as-cran
      - run:
          name: Move R built package
          command: mkdir built && mv oysteR_*.tar.gz built
      - store_artifacts:
          path: ~/oysteR/oysteR.Rcheck/
      - store_artifacts:
          path: ~/oysteR/built/

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
